import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


def main():
    # imports csv file from specified file location
    indeed_data = pd.read_csv("C:/File/Location.csv")

    # cleans the data of resumes containing zero gender-connoted words and empty resumes
    indeed_data.drop(indeed_data[indeed_data['male-per'] == 0][indeed_data['female-per'] == 0].index, inplace = True)
    indeed_data.drop(indeed_data[indeed_data['empty'] == 'Yes'].index, inplace=True)

    # defines the x and y values for regression
    x = indeed_data.iloc[:, 12].values.reshape(-1, 1)
    y = indeed_data.iloc[:, 1]

    # runs regression
    model = LinearRegression()
    model.fit(x, y)
    indeed_predict = model.predict(x)

    # creates a scatter plot of male-percentage relative to rank
    fig = plt.figure()
    plt.rcParams['figure.figsize'] = (10, 6)
    plt.scatter(x, y)

    # plots the line generated by linear regression
    plt.plot(x, indeed_predict, color='blue', linewidth = 3)
    plt.xlabel("Male Percentage")
    plt.ylabel("Rank")
    fig.suptitle("All Resumes Data", fontsize=16)
    plt.show()

    # prints mean squared error and variance score
    print('Coefficients: \n', model.coef_)
    print("Mean squared error: %.2f"
          % mean_squared_error(y, indeed_predict))
    print('Variance score: %.2f' % r2_score(y, indeed_predict))


if __name__ == '__main__':
    main()
